Repository Mayank0255/Stackoverflow-Clone-Backend, pull requests merged in 2022-03, with the labels that each got.

#35 feat: Api Architecture Improvement
  index.js
Labels: enhancement

#40 fix: tags and posts bugs
  src/constants.js
  src/controllers/posts.controller.js
  src/helpers/investApi.js
  src/repositories/posts.repository.js
  src/routers/posts.router.js
  src/services/posts.service.js
Labels: bug

#41 Feature/multiple tags 1
  .eslintrc.json
  src/controllers/posts.controller.js
  src/helpers/format.js
  src/helpers/index.js
  src/repositories/answers.repository.js
  src/repositories/comments.repository.js
  src/repositories/posts.repository.js
  src/repositories/tags.repository.js
  src/repositories/users.repository.js
  src/routers/posts.router.js
  src/services/posts.service.js
Labels: enhancement, feature

#43 Improvement - Call stackexchange tags API with all the entered tags.
  src/helpers/investApi.js
  src/repositories/posts.repository.js
Labels: enhancement

#44 add validation for tags
  src/repositories/posts.repository.js
Labels: enhancement

#45 Chore/eslint action 1
  .github/workflows/lint-check.yml
  index.js
  package.json
  src/helpers/investApi.js
  src/repositories/posts.repository.js
  src/routers/comments.router.js
  src/services/index.js
  src/services/posts.service.js
Labels: CI
